name: Cypress Test Run


on:

  push:

    branches:
      - main



jobs:


  test:


    runs-on: ubuntu-latest


    steps:


      - name: Checkout code
        uses: actions/checkout@v4



      - name: Install Node
        uses: actions/setup-node@v4

        with:

          node-version: 20



      - name: Install dependencies
        run: npm install



      - name: Run Cypress Test
        if: always()
        run: npx cypress run



      - name: Merge Cypress Reports
        if: always()

        run: |

          npx mochawesome-merge cypress/reports/*.json > cypress/reports/report.json



      - name: Generate HTML Report
        if: always()
        run: |
         npx marge cypress/reports/report.json \
            --reportDir cypress/reports/html \
            --inline



      - name: Check Report
        if: always()

        run: |

          ls -lh cypress/reports/html

          wc -c cypress/reports/html/index.html



      - name: Upload Cypress Report
        if: always()

        uses: actions/upload-artifact@v4

        with:

          name: Cypress-Test-Report

          path: cypress/reports/html



      - name: Send Report Email
        if: always()
        env:
        EMAIL: ${{ secrets.EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: node sendReport.js